---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    targetRevision: main
    path: system
    repoURL: https://github.com/frealmyr/homelab-apps
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: entertainment
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    targetRevision: main
    path: entertainment
    repoURL: https://github.com/frealmyr/homelab-apps
