apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-system
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: default
  project: default
  source:
    path: system
    repoURL: https://github.com/frealmyr/homelab-apps
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
