---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.fmlab.no`)
      priority: 10
      services:
        - name: argocd-server
          port: 80
      middlewares:
        - name: traefik-system-security@kubernetescrd
        - name: traefik-system-sso@kubernetescrd
    - kind: Rule
      match: Host(`argocd.fmlab.no`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
  tls:
    secretName: argocd-server

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: http-redirect
  namespace: traefik-system
spec:
  entryPoints:
    - web
  routes:
    - match: HostRegexp(`{host:.+fmlab.no}`)
      kind: Rule
      middlewares:
        - name: https_redirect
        - name: security
      services:
        - name: traefik
          port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: traefik-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`traefik.fmlab.no`)
      kind: Rule
      middlewares:
        - name: security
      services:
        - name: api@internal
          kind: TraefikService
  tls:
    secretName: traefik-dashboard
