apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingressroutes/argocd.yml
  - ingressroutes/http-redirect.yml
  - ingressroutes/traefik-dashboard.yml
  - middlewares/https-redirect.yml
  - middlewares/security.yml
  - traefik-forward-auth/certificate.yml
  - traefik-forward-auth/deployment.yml
  - traefik-forward-auth/ingress.yml
  - traefik-forward-auth/middleware.yml
  - traefik-forward-auth/service.yml
