apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-items
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: monitoring
  project: default
  source:
    targetRevision: main
    path: system/cert-manager-items
    repoURL: https://github.com/frealmyr/homelab-apps

