apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-forward-auth
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: monitoring
  project: default
  source:
    targetRevision: main
    path: system/traefik-forward-auth
    repoURL: https://github.com/frealmyr/homelab-apps
