apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: monitoring
  project: default
  source:
    targetRevision: main
    path: system/prometheus
    repoURL: https://github.com/frealmyr/homelab-apps
    helm:
      releaseName: prometheus
      valueFiles:
      - default.yaml
